const data = getData();
const el = selector => document.querySelector(selector);
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
el('#year').textContent = new Date().getFullYear();
el('#project-count').textContent = `${data.projects.length}+`;
el('#skill-count').textContent = `${data.skills.length}+`;
el('#cert-count').textContent = `${data.certificates.length}+`;
let active = 'Semua'; let showAllCertificates = false;
function projectImages(project) { return [project.thumbnail, ...(Array.isArray(project.gallery) ? project.gallery : [])].filter(Boolean); }
function projectImage(project) { const images = projectImages(project); return images.length ? `<button class="project-visual" data-gallery="${project.id}" aria-label="Lihat galeri ${escapeHtml(project.nama_proyek)}"><img class="project-image" src="${images[0]}" alt="${escapeHtml(project.nama_proyek)}">${images.length > 1 ? `<span class="image-count">▧ ${images.length} foto</span>` : ''}</button>` : `<div class="project-art"><span>${escapeHtml(project.kategori_id)}</span></div>`; }
function renderProjects() { const standardCategories = ['Semua', 'Website', 'UI/UX Design', 'Mobile App', 'Video', 'Photography']; const categories = [...new Set([...standardCategories, ...data.projects.map(project => project.kategori_id)])]; el('#filters').innerHTML = categories.map(category => `<button class="filter ${category === active ? 'active' : ''}" data-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`).join(''); const items = active === 'Semua' ? data.projects : data.projects.filter(project => project.kategori_id === active); el('#project-list').innerHTML = items.length ? items.map(project => `<article class="project-card reveal">${projectImage(project)}<div class="card-body"><p class="tag">${escapeHtml(project.kategori_id)}</p><h3>${escapeHtml(project.nama_proyek)}</h3><p>${escapeHtml(project.deskripsi_singkat)}</p><span class="project-year">${escapeHtml(project.tahun)} · ${escapeHtml(project.status)}</span></div></article>`).join('') : '<p class="empty-state">Belum ada proyek pada kategori ini.</p>'; document.querySelectorAll('.filter').forEach(button => button.onclick = () => { active = button.dataset.category; renderProjects(); }); document.querySelectorAll('[data-gallery]').forEach(button => button.onclick = () => openGallery(data.projects.find(project => String(project.id) === button.dataset.gallery))); revealElements(); }
function renderSkills() { el('#skill-list').innerHTML = data.skills.map(skill => `<article class="skill reveal">${skill.gambar ? `<img src="${skill.gambar}" alt="${escapeHtml(skill.nama)}">` : `<b>${escapeHtml(skill.ikon || 'SK')}</b>`}<span>${escapeHtml(skill.nama)}</span></article>`).join(''); }
function renderCertificates() { const visible = showAllCertificates ? data.certificates : data.certificates.slice(0, 3); el('#certificate-list').innerHTML = visible.length ? visible.map(certificate => `<article class="certificate reveal">${certificate.gambar ? `<img class="certificate-image" src="${certificate.gambar}" alt="${escapeHtml(certificate.nama_sertifikat)}">` : '<div class="cert-icon">✦</div>'}<div><p class="tag">${escapeHtml(certificate.penerbit)}</p><h3>${escapeHtml(certificate.nama_sertifikat)}</h3><p>${escapeHtml(certificate.tahun)}</p>${certificate.tautan_sertifikat ? `<a href="${certificate.tautan_sertifikat}" target="_blank" rel="noreferrer">Lihat kredensial ↗</a>` : ''}</div></article>`).join('') : '<p class="empty-state">Belum ada sertifikat.</p>'; el('#certificate-actions').innerHTML = data.certificates.length > 3 ? `<button class="secondary-action see-all" type="button">${showAllCertificates ? 'Tampilkan lebih sedikit' : 'Lihat semua sertifikat'} (${data.certificates.length})</button>` : ''; const button = el('.see-all'); if (button) button.onclick = () => { showAllCertificates = !showAllCertificates; renderCertificates(); }; revealElements(); }
function openGallery(project) { if (!project) return; const images = projectImages(project); if (!images.length) return; const modal = el('#gallery-modal'); const view = el('#gallery-image'); const thumbs = el('#gallery-thumbs'); const select = source => { view.src = source; view.alt = project.nama_proyek; thumbs.querySelectorAll('button').forEach(button => button.classList.toggle('active', button.dataset.source === source)); }; thumbs.innerHTML = images.map((source, index) => `<button data-source="${source}" class="${index === 0 ? 'active' : ''}"><img src="${source}" alt="Foto ${index + 1}"></button>`).join(''); thumbs.querySelectorAll('button').forEach(button => button.onclick = () => select(button.dataset.source)); select(images[0]); modal.showModal(); }
el('.gallery-close').onclick = () => el('#gallery-modal').close(); el('#gallery-modal').onclick = event => { if (event.target === el('#gallery-modal')) el('#gallery-modal').close(); };
function revealElements() { document.querySelectorAll('.reveal').forEach((element, index) => { element.style.setProperty('--delay', `${Math.min(index * 55, 330)}ms`); element.classList.add('is-visible'); }); }
renderProjects(); renderSkills(); renderCertificates();
el('.menu').onclick = () => el('.portfolio-nav').classList.toggle('open');
window.addEventListener('load', () => { document.body.classList.remove('is-loading'); revealElements(); });
